---
title: "Reading Data from the Web"
author: "Maya Krishnamoorthy"
date: "2024-10-10"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

Load the necessary libraries.

```{r}
library(rvest)
library(httr)
```

## Extracting tables

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```

Get the pieces I actually need.

```{r}
marj_use_df = 
  drug_use_html |> 
  html_table() |> # from rvest package, pulls out all tables on the page
  first() |> # takes first element out - for us it outputs the first table
  slice(-1)

marj_use_df
```

## Learning assessment
Read in cost of living data.

```{r}
nyc_cost_df =
  read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") |> 
  html_table(header = TRUE) |> # tell html that the first row is the header
  first()

nyc_cost_df
```

## CSS Selectors

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)

swm_title_vec = 
  swm_html |> 
  html_elements(".ipc-title-link-wrapper .ipc-title__text") |> 
  html_text()

# run time
swm_runtime_vec = 
  swm_html |> 
  html_elements(".dli-title-metadata-item:nth_child(2)") |> 
  html_text()

swm_score_vec = 
  swm_html |> 
  html_elements(".metacritic-score-box") |> 
  html_text()

swm_df = 
  tibble(
    title = swm_title_vec,
    runtime = swm_runtime_vec,
    score = swm_score_vec
  )
```

## Learning assessment 2
Books: Use a process similar to the one above to extract the book titles, stars, and prices

```{r}
books_url = "https://books.toscrape.com/"
books_html = read_html(books_url)

books_titles = 
  books_html |> 
  html_elements("h3") |> 
  html_text2()

books_stars = 
  books_html |>
  html_elements(".star-rating") |>
  html_attr("class")

books_price = 
  books_html |>
  html_elements(".price_color") |>
  html_text()

books = tibble(
  title = books_titles,
  stars = books_stars,
  price = books_price
)
```


